ACCOUNTS/urls.py
from django.urls import include,path
from django.contrib.auth import views as auth_views
from . import views as ACCOUNTS_VIEWS

app_name="ACCOUNTS" 



urlpatterns=[
	path('signup/',ACCOUNTS_VIEWS.signup,name='signup'),
	
	path('login/',auth_views.LoginView.as_view(template_name='ACCOUNTS/login.html'),name='login'),

	path('logout/',auth_views.LogoutView.as_view(),name='logout'),


]

EVENTS/urls.py
from django.urls import include, path

app_name = "EVENTS"

from . import views as EVENTS_VIEWS

urlpatterns = [ 
				path('proiect/<int:proiect_pk>/template/',EVENTS_VIEWS.eveniment_template_nou,name='eveniment_template_nou'),
				path('eveniment_template/<int:eveniment_pk>/',EVENTS_VIEWS.detalii_eveniment_template,name='detalii_eveniment_template'),				
				path('eveniment_template/<int:eveniment_pk>/finalizeaza_eveniment/',EVENTS_VIEWS.finalizeaza_eveniment,name='finalizeaza_eveniment'),
				

]

PROJECTS/urls.py
from django.urls import include, path

app_name = "PROJECTS"

from . import views as PROJECTS_VIEWS

urlpatterns = [ path('home/',PROJECTS_VIEWS.home,name='projects_home'),
				path('new_project/',PROJECTS_VIEWS.new_project,name='new_project'),
				path('project_details/<int:pk>/',PROJECTS_VIEWS.project_details,name='project_details'),
				
				
]

SCHEDULER/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

        path('admin/', admin.site.urls, name='admin'), # logarea ca si administrator 
        
        path('events/', include("EVENTS.urls")),
        path('projects/', include("PROJECTS.urls")),
        path('account/',include("ACCOUNTS.urls")),

]

PROJECTS/models.py
from django.db import models

# Create your models here.


class Proiect (models.Model):

	nume=models.CharField(max_length=30,unique=True)
	id_proiect=models.IntegerField(unique=True)
	descriere=models.CharField(max_length=100)



	def __str__(self):
		return self.nume

PROJECTS/forms.py
from django import forms
from PROJECTS.models import Proiect

class Proiect_ADD(forms.ModelForm):
	nume=forms.CharField(max_length=30,label='Introduceti numele Proiectului',widget=forms.TextInput(attrs={'placeholder':'Nume Proiect'}))
	id_proiect=forms.IntegerField(label='ID inregistrare Proiect',widget=forms.NumberInput(attrs={'placeholder':'ID Proiect'}))
	descriere=forms.CharField(max_length=100,label='Descirerea Proiectului',widget=forms.TextInput(attrs={'placeholder':'Descriere Proiect'}))


	class Meta :
		model=Proiect
		fields=['nume','id_proiect','descriere']

PROJECTS/views.py
from django.shortcuts import render,redirect
from .models import Proiect
from EVENTS.models import Eveniment_Template,Eveniment
from .forms import Proiect_ADD
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from ACCOUNTS.models import Employee
# Create your views here.
from django.contrib.auth.decorators import login_required


@login_required
def home(request):

	user_req = request.user
	employee_req=Employee.objects.get(user=user_req)
	proiecte_querry_req=Proiect.objects.all()


	paginator = Paginator(proiecte_querry_req, 25) 

	page_number = request.GET.get('page')
	proiecte_querry = paginator.get_page(page_number)
   


	evenimente_q=Eveniment.objects.filter(responsabil=user_req,status=False)


	return render(request,'PROJECTS/home.html',{'proiecte_querry':proiecte_querry,'employee':employee_req,'queue_tasks':evenimente_q})


@login_required
def new_project(request):
	if request.method=="POST":
		form=Proiect_ADD(request.POST)
		if form.is_valid():
			form.save()
			return redirect('PROJECTS:projects_home')
	else:
		form=Proiect_ADD()
	return render(request,'PROJECTS/proiectnou.html',{'form':form})


@login_required
def project_details(request,pk):
	proiect_querry=Proiect.objects.get(pk=pk)
	eveniment_template_querry_req=Eveniment_Template.objects.filter(proiect=proiect_querry)



	paginator = Paginator(eveniment_template_querry_req, 20)

	page_number = request.GET.get('page')
	eveniment_template_querry = paginator.get_page(page_number)


	return render(request,'PROJECTS/proiect_detalii.html',{'proiect':proiect_querry,'eveniment_template':eveniment_template_querry})

templates/PROJECTS/home.html
{% extends 'PROJECTS/template.html' %}


{% block content %}



<div class="container_home">

<div class="container_left_home">

	<div class="nume">Nume: {{employee.user.username}}</div>
	<hr/>
	<div class="zona">Zona/Dep.: {{employee.Zona}} / {{employee.department}}</div>
	<hr/>
	<div class="zona">Saricini de efectuat :</div>
	
{% for task in queue_tasks %}
<div class="task">
<button type="button" class="collapsible">{{task}}</button>
<div class="content">
  <p>Proiect :</p>
  <p>{{task.eveniment_template.proiect}}</p>
  <hr/>	
  <p>Actiune:</p>
  <p>{{task.eveniment_template.activitati_necesare}}</p>
  <hr/>
  <p>Termen Finalizare:</p>
  <p>{{task.data_finalizare}} </p>
  <hr/>
  <p>Finalizare Actiune:</p>
 <button class="finalizeaza_buton"  ><a href="{% url 'EVENTS:finalizeaza_eveniment' task.pk %}">Finalizeaza</a></button>
</div>
</div>


	
{% endfor %}

</div>



	<div class="container_right">

		<div class="row_title">
			PROIECTE 
		</div> 


		<div class="row">
			<div class="column_id">ID</div>
			<div class="column_nume">NUME</div>
			<div class="column_proiect_id">ID </div>
			<div class="column_descriere">DESCRIERE</div>
			<div class="column_evenimente"></div>
		</div>

	

		{% for proiect in proiecte_querry%}

		<div class="row">
			<div class="column_id">{{proiect.id}} </div>
			<div class="column_nume">{{proiect.nume}}</div>
			<div class="column_proiect_id">{{proiect.id_proiect}} </div>
			<div class="column_descriere">{{proiect.descriere}} </div>
			<div class="column_evenimente"><a href="{% url 'PROJECTS:project_details' proiect.pk %}">Lista Evenimente </a></div>
		</div> 
		

		{% endfor %}


		



		<div class="row_footer">
			<a href="{% url 'PROJECTS:new_project'  %}">Adauga Proiect</a>
		</div> 


<div class="pagination">
    <span class="step-links">
        {% if proiecte_querry.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ proiecte_querry.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ proiecte_querry.number }} of {{ proiecte_querry.paginator.num_pages }}.
        </span>

        {% if proiecte_querry.has_next %}
            <a href="?page={{ proiecte_querry.next_page_number }}">next</a>
            <a href="?page={{ proiecte_querry.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>		
	
	</div>




</div>


<script>

/** SCRIPTUL PENTRU COLLAPSE BUTTON EVENIMENTE ACTIVE **/

var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}

</script>



{% endblock %}

templates/PROJECTS/proiect_detalii.html
{% extends 'PROJECTS/template.html' %}

{% block content %}









<div class="container_detalii">



<div class="container_left_detalii">

	<div class="nume">Proiect: {{proiect.nume}}</div>
	<hr/>
	<div class="ID">Proiect: {{proiect.id_proiect}}</div>
	<hr/>
	<div class="descriere">{{proiect.descriere}}</div>
	<hr/>

</div>




<div class="container_right_detalii">




		<div class="row_title_detalii">
			SARCINI DE EFECTUAT
		</div> 


		<div class="row_detalii">
			<div class="column_id_ev">ID</div>
			<div class="column_nume_ev">NUME</div>
			<div class="column_recurenta_zile_ev">RECURENTA </div>
			<div class="column_status_ev">STATUS</div>
			<div class="column_evenimente_ev"></div>
		</div>



		{% for eveniment in eveniment_template %}

		<div class="row_detalii">
			<div class="column_id_ev">{{eveniment.id}} </div>
			<div class="column_nume_ev">{{eveniment.nume}}</div>
			<div class="column_recurenta_zile_ev">{{eveniment.recurenenta_zile}} Zile </div>

			{% if eveniment.status == True %}
			<div class="column_status_ev">Activ</div>
			{% else %}
			<div class="column_status_ev">Inactiv</div>
			{% endif %}
			<div class="column_evenimente_ev"><a href="{% url 'EVENTS:detalii_eveniment_template' eveniment.pk %}">DETALII</a></div>
		</div> 
	

		{% endfor %}


		



		<div class="row_footer_detalii">
			<a href="{% url 'EVENTS:eveniment_template_nou' proiect.pk  %}">Adauga O Sarcina </a>
		</div> 




<div class="pagination">
    <span class="step-links">
        {% if eveniment_template.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ eveniment_template.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ eveniment_template.number }} of {{ eveniment_template.paginator.num_pages }}.
        </span>

        {% if eveniment_template.has_next %}
            <a href="?page={{ eveniment_template.next_page_number }}">next</a>
            <a href="?page={{ eveniment_template.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>		




</div>




</div>



	

{% endblock %}

templates/PROJECTS/proiectnou.html
{% extends 'PROJECTS/template.html' %}


{% block content %}
<div class="container_proiect_nou">




<div class="container_left_proiect_nou">
    <div class="nume">ADAUGA PROIECT NOU</div>
    <hr/>
</div>





<div class="container_right_proiect_nou">

 	<div class="proiect_nou_form">

                <div class="title_form">
                    Inregistrare Proiect
                </div>      



  				<form method="post" name="new_proiect">

                {% csrf_token %}

                {% for field in form %}
                	<div class="form_row">

                        <div class="form_col_label">
                        {{ field.label}}
                        </div>
                        
                	   <div class="form_col_value">
                	   {{ field}}
                	   </div>
                   
                	</div> 

                    <hr/>
                {% endfor %}



                <div class="form_row">
                    <button type="submit" class="btn_form">Adauga</button>
                </div>

               </form>

            	

    </div>



</div>





</div>

{% endblock %}

 

templates/PROJECTS/template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>

	<link href="{% static 'css/PROJECTS/style.css' %}" rel="stylesheet" type="text/css"> 
	<script src="{% static 'js/PROJECTS/scripts.js' %}"></script> 
	

</head>
<body>


	<div class="navbar">
		<div class="navbar_left">
			<a class="navbutton" href="{% url 'PROJECTS:projects_home' %}">SchedullingApp</a>
		</div>
		<div class="navbar_right">
			  	<div class="dropdown">
  					<a class="navbutton" href="{% url 'ACCOUNTS:logout' %}">Delogare</a>
 
  				</div> 
		</div>
	</div>


	{% block content %}
	{% endblock %}

</body>
</html>