ACCOUNTS/urls.py
from django.urls import include,path
from django.contrib.auth import views as auth_views
from . import views as ACCOUNTS_VIEWS

app_name="ACCOUNTS" 



urlpatterns=[
	path('signup/',ACCOUNTS_VIEWS.signup,name='signup'),
	
	path('login/',auth_views.LoginView.as_view(template_name='ACCOUNTS/login.html'),name='login'),

	path('logout/',auth_views.LogoutView.as_view(),name='logout'),


]

EVENTS/urls.py
from django.urls import include, path

app_name = "EVENTS"

from . import views as EVENTS_VIEWS

urlpatterns = [ 
				path('proiect/<int:proiect_pk>/template/',EVENTS_VIEWS.eveniment_template_nou,name='eveniment_template_nou'),
				path('eveniment_template/<int:eveniment_pk>/',EVENTS_VIEWS.detalii_eveniment_template,name='detalii_eveniment_template'),				
				path('eveniment_template/<int:eveniment_pk>/finalizeaza_eveniment/',EVENTS_VIEWS.finalizeaza_eveniment,name='finalizeaza_eveniment'),
				

]

PROJECTS/urls.py
from django.urls import include, path

app_name = "PROJECTS"

from . import views as PROJECTS_VIEWS

urlpatterns = [ path('home/',PROJECTS_VIEWS.home,name='projects_home'),
				path('new_project/',PROJECTS_VIEWS.new_project,name='new_project'),
				path('project_details/<int:pk>/',PROJECTS_VIEWS.project_details,name='project_details'),
				
				
]

SCHEDULER/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

        path('admin/', admin.site.urls, name='admin'), # logarea ca si administrator 
        
        path('events/', include("EVENTS.urls")),
        path('projects/', include("PROJECTS.urls")),
        path('account/',include("ACCOUNTS.urls")),

]

ACCOUNTS/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Employee(models.Model):


    DEP_CHOICES = [
        ('Productie', 'Productie'),
        ('Mentenanta', 'Mentenanta'),
        ('Admin' , 'Admin'),

    ]


    ZONA_CHOICES = [
        ('Asamblare', 'Asamblare'),
        ('Airbag', 'Airbag'),
        ('Foaming' , 'Foaming'),
        ('Diecasting' , 'Diecasting'),
        ('LW' , 'LW'),
        ('IMO' , 'IMO'),
        ('Toolshop' , 'Toolshop'),
        ('Toate' , 'Toate'),

    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100, choices=DEP_CHOICES)
    Zona = models.CharField(max_length=100, choices=ZONA_CHOICES)


    def __str__(self):
        return self.user.username

ACCOUNTS/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm 
from django.contrib.auth.models import User

from .models import Employee 









class RegistrationForm(UserCreationForm):
    

    DEP_CHOICES = [
        ('Productie', 'Productie'),
        ('Mentenanta', 'Mentenanta'),
       
    ]


    ZONA_CHOICES = [
        ('Asamblare', 'Asamblare'),
        ('Airbag', 'Airbag'),
        ('Foaming' , 'Foaming'),
        ('Diecasting' , 'Diecasting'),
        ('LW' , 'LW'),
        ('IMO' , 'IMO'),
        ('Toolshop' , 'Toolshop'),
        ('Toate' , 'Toate'),

    ]

   
    department = forms.ChoiceField(choices=DEP_CHOICES,label='Selectati departamentul')
    Zona = forms.ChoiceField(choices=ZONA_CHOICES,label='Selectati aria')




    class Meta: 
        model = User
        fields = (
            'username', 'password1', 'password2' ,
            'department',
            'Zona',


        )
        labels = {
        'username': ('Utilizator'),
        'password1': ('Parola'),
        'password2': ('Repeta Parola'),
        'department': ('Selectati departamentu'),
        'Zona': ('Selectati aria'),
        }
        

ACCOUNTS/views.py
from django.contrib.auth import login 
from django.shortcuts import render, redirect
from .forms import  RegistrationForm
from django.contrib import messages
from django.contrib.auth.models import User
from .models import Employee
from django.http import HttpResponse , request



from django.contrib import messages






def home(request):

    return render(request,'ACCOUNTS/home.html')





def signup(request):

	if request.method=='POST':
		form=RegistrationForm(request.POST)
		if form.is_valid():
			new_user=form.save()
			new_user_name=form.cleaned_data['username']
			employee_department=form.cleaned_data['department']
			employee_zona=form.cleaned_data['Zona']
			Employee_enq=Employee.objects.create(user=new_user,department=employee_department,Zona=employee_zona)
			Employee_enq.save()
			messages.success(request,'Inregistrare utilizator cu success : ' +str(new_user_name) )
		else:
			messages.success(request,'Utilizatorul nu a fost inregistrat, a aparut o eroare.Verificati Numele si Parola.' )
		return redirect('PROJECTS:projects_home')

	else:


		form=RegistrationForm()
	return render(request,'ACCOUNTS/signup.html',{'form':form})

templates/ACCOUNTS/login.html
{% extends 'ACCOUNTS/template.html' %}


{% block content %}





<div class="container_login">




		  <div class="login_form">



		  		<div class="row_title">
				AUTENTIFICARE
				</div> 


  				<form method="post" name="login">
                {% csrf_token %}

                {% for field in form %}
                	<div class="form_row">

                    <div class="form_col_label">
                    {{ field.label}}
                    </div>
                        
                	<div class="form_col_value">
                	{{ field}}
                	</div>
                   
                	</div> 
                     <hr/>
                {% endfor %}
                <div class="form_row">
                 <button type="submit" class="btn_form">Logare</button>
                </div>
                </form>
           </div>	



        <div class="row_footer">

			<a href="{% url 'ACCOUNTS:signup' %}" > Inregistreaza Utilizat Nou!</a>
		</div> 

	
	




</div>


{% endblock %}

templates/ACCOUNTS/signup.html
{% extends 'ACCOUNTS/template.html' %}


{% block content %}





<div class="container_register">






		  <div class="register_form">


		  	<div class="row_title">
			INREGISTRARE
			</div> 


  				<form method="post" name="login">
                {% csrf_token %}

                {% for field in form %}
                	<div class="form_row">

                    <div class="form_col_label">
                    {{ field.label}}
                    </div>
                        
                	<div class="form_col_value">
                	{{ field}}
                	</div>
                   
                	</div> 
                     <hr/>
                {% endfor %}
                <div class="form_row">
                 <button type="submit" class="btn_form">INREGISTRARE</button>
                </div>
                </form>
           </div>	



        <div class="row_footer">

			<a href="{% url 'ACCOUNTS:login' %}" > Esti deja Utilizator ? Autentifica-te!</a>
		</div> 






</div>


{% endblock %}

templates/ACCOUNTS/template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>

	<link href="{% static 'css/ACCOUNTS/style.css' %}" rel="stylesheet" type="text/css"> 

</head>
<body>


	<div class="navbar">
						<a class="navbutton" href="{% url 'PROJECTS:projects_home' %}">SchedullingApp</a>
			
	</div>


	{% block content %}
	{% endblock %}

</body>
</html>